version: "3.4"

services:
  ticketmanagement.ui:
    image: darkbdochub/ticketmanagement.ui:latest
    ports:
      - "3000:80"
    environment:
      - FeatureManagement:React=true
    depends_on:
      - events.api
      - users.api
      - orders.api
    container_name: ticketmanagement.ui

  events.api:
    image: darkbdochub/events.api:latest
    ports:
      - "7001:443"
      - "5001:80"
    environment:
      - ConnectionStrings:DefaultConnection=Server=sqldb;Database=mydatabase;User=sa;Password=Admin!1admin
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_HTTPS_PORT=7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/mnt/c/https/aspnetapp.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/mnt/c/https:ro
    depends_on:
      - sqldb
    container_name: events.api

  users.api:
    image: darkbdochub/users.api:latest
    ports:
      - "5002:80"
      - "7002:443"
    environment:
      - ConnectionStrings:DefaultConnection=Server=sqldb;Database=mydatabase;User=sa;Password=Admin!1admin
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/mnt/c/https/aspnetapp.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/mnt/c/https:ro
    depends_on:
      - sqldb
    container_name: users.api

  orders.api:
    image: darkbdochub/orders.api:latest
    ports:
      - "5003:80"
      - "7003:443"
    environment:
      - ConnectionStrings:DefaultConnection=Server=sqldb;Database=mydatabase;User=sa;Password=Admin!1admin
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/mnt/c/https/aspnetapp.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/mnt/c/https:ro
    depends_on:
      - sqldb
    container_name: orders.api

  sqldb:
    image: darkbdochub/sqldb:latest
    ports:
      - "5433:1433"
    container_name: sqldb
