name: TicketManagement-test

on:
  push:
    branches:
      - task-5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
        with:
          version: latest
      - name: Push TicketManagement packages
        run: octo push --server="http://tm.octo.com/" --apiKey="API-RKM2J2QNUPCKZ5N5Y73UDNOPJ5GP4KCJ"
