name: TicketManagement

on:
  push:
    branches:
      - task-6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore ./TicketManagement.sln
      - name: Build
        run: dotnet build TicketManagement.MVC/TicketManagement.MVC.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Create artifacts folder
        run: |
          mkdir "$GITHUB_WORKSPACE/artifacts"
          mkdir "$GITHUB_WORKSPACE/artifacts/TicketManagement.Database"
          mkdir "$GITHUB_WORKSPACE/artifacts/TicketManagement.MVC"
          mkdir "$GITHUB_WORKSPACE/artifacts/TicketManagement.EventManagement.API"
          mkdir "$GITHUB_WORKSPACE/artifacts/TicketManagement.UserManagement.API"
          mkdir "$GITHUB_WORKSPACE/artifacts/TicketManagement.OrderManagement.API"
      - name: Publish OctoPetShopDatabase
        run: dotnet publish TicketManagement.Database/TicketManagement.Database.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/TicketManagement.Database"
      - name: Publish OctoPetShopWeb
        run: dotnet publish TicketManagement.MVC/TicketManagement.MVC.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/TicketManagement.MVC"
      - name: Publish OctoPetShopProductService
        run: dotnet publish TicketManagement.EventManagement.API/TicketManagement.EventManagement.API.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/TicketManagement.EventManagement.API"
      - name: Publish OctoPetShopShoppingCartService
        run: dotnet publish TicketManagement.UserManagement.API/TicketManagement.UserManagement.API.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/TicketManagement.UserManagement.API"
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
        with:
          version: latest
      - name: Package OctoPetShopDatabase
        run: |
          octo pack --id="OctoPetShop.Database" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/TicketManagement.Database" --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: Package OctoPetShopWeb
        run: |
          octo pack --id="OctoPetShop.Web" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/TicketManagement.MVC" --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: Package OctoPetShopProductService
        run: |
          octo pack --id="OctoPetShop.ProductService" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/TicketManagement.EventManagement.API" --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: Package OctoPetShopShoppingCartService
        run: |
          octo pack --id="OctoPetShop.ShoppingCartService" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/TicketManagement.UserManagement.API" --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: Push OctoPetShop packages
        uses: OctopusDeploy/push-package-action@v1.1.1
        with:
          api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          server: ${{ secrets.OCTOPUSSERVERURL }}
          packages: "artifacts/TicketManagement.Database.${{ env.PACKAGE_VERSION }}.zip,artifacts/TicketManagement.MVC.${{ env.PACKAGE_VERSION }}.zip,artifacts/TicketManagement.EventManagement.API.${{ env.PACKAGE_VERSION }}.zip,artifacts/TicketManagement.UserManagement.API.${{ env.PACKAGE_VERSION }}.zip"
          space: ${{ secrets.OCTOPUSSERVER_SPACE }}
      - name: Create and deploy release
        uses: OctopusDeploy/create-release-action@v1.1.1
        with:
          api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          server: ${{ secrets.OCTOPUSSERVERURL }}
          space: ${{ secrets.OCTOPUSSERVER_SPACE }}
          project: "Octo Pet Shop"
          deploy_to: "Dev"
          progress: true
